theme: jekyll-theme-minimal
title: Pedal
description: Pedal seeks to replace Outdoor Recreation's current bike service system with a modern and mobile alternative.
logo: /Pedal.github.io/docs/assets/logo.png
